name: Build

on:
  workflow_call: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
