on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

      - name: Checkout Repository
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        if: ${{ steps.release.outputs.releases_created }}
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Build packages
        if: ${{ steps.release.outputs.releases_created }}
        run: make

      - name: Publish @aitoolkit/cache
        if: ${{ steps.release.outputs['packages/cache--releases_created'] }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/cache
          npm publish

      - name: Publish @aitoolkit/complete
        if: ${{ steps.release.outputs['packages/complete--releases_created'] }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/complete
          npm publish

      - name: Publish @aitoolkit/search
        if: ${{ steps.release.outputs['packages/search--releases_created'] }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/search
          npm publish
