on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - packages/cache
          - packages/complete
          - packages/search
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
    outputs:
      publish-packages/cache:
        ${{ steps.release.outputs['packages/cache--releases_created'] }}
      publish-packages/complete:
        ${{ steps.release.outputs['packages/complete--releases_created'] }}
      publish-packages/search:
        ${{ steps.release.outputs['packages/search--releases_created'] }}

  publish:
    runs-on: ubuntu-latest
    needs: release-please
    strategy:
      matrix:
        package:
          - packages/cache
          - packages/complete
          - packages/search
    if:
      ${{ needs.release-please.outputs[format('publish-{0}', matrix.package)] }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Publish ${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd ${{ matrix.package }}
          npm install
          npm prepublish
          npm publish
